# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec78213f2bd75cacba3ce5a1f18c557de954b8adc132549efe9101e7fb98f85f8c981ea0b29fbdc3e2796ab491f22816be221db6ba957b7977d3daa423fe573

test:
  secret_key_base: 3ad442671445588b19ae8cbd2536620adcceac1a206893426030fc271ba4dc69b77b3257404dcbc985571aeaa17a54cbb759f037f545f53e791b7d6df294a2de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
